### PR TITLE
Replace `structopt` with `clap`

### PR DESCRIPTION
**Pull request by Expyron**

### CODE REVIEW

**Comment by Stranger6667** [comment]
What is the reason for this change?

**Comment by Expyron** [comment]
Structopt is not maintained anymore: https://github.com/TeXitoi/structopt/issues/525
Its author recommends moving to clap v3.

**Comment by Julian** [comment]
As is I think this also is triggering GitHub security warnings for users of `jsonschema-rs` -- e.g. on bowtie, due to the transitive dependency on `ansi_term`, I see:

Screen Shot 2022-09-17 at 14 47 01

**Comment by Stranger6667** [comment]
Sorry for the delay! Merged :) I'll make a new release soon

**Pull request merged**
